"""fix tables

Revision ID: 5da7e86a795c
Revises: 2f22615cc5e8
Create Date: 2020-08-07 19:45:18.635863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da7e86a795c'
down_revision = '2f22615cc5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
