"""Added image_url attribute to Post schema

Revision ID: 95e637315724
Revises: 0a3a01c62e38
Create Date: 2020-08-29 16:30:50.590762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95e637315724'
down_revision = '0a3a01c62e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_url', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_url')
    # ### end Alembic commands ###
